cog<-read.csv("/Users/DELL/Documents/GH????/Cognitive_reserve_ly.csv")
View(cog)
library(mediation)
model.asso1<-lm(cog_re_tri~score_tri3, data = cog)
model.asso2<-lm(ci~cog_re_tri+score_tri3, data = cog)
med.out<-mediate(model.asso1,model.asso2,treat = "score_tri3",mediator = "cog_re_tri", sims = 100, robustSE = TRUE)
model.ad1<-lm(cog_re_tri~score_tri3+trueage+gender+residence+marital+ethnicity+cog$srhealth, data = cog)
model.ad2<-lm(ci~score_tri3+cog_re_tri+score_tri3+trueage+gender+residence+marital+ethnicity+cog$srhealth, data = cog)
med.ad<-mediate(model.ad1,model.ad2,treat = "score_tri3",mediator = "cog_re_tri", sims = 100, robustSE = TRUE)
summary(med.ad)
